-- =============================================================
-- Seed: Quick Lists — 100 Indonesian Cuisines + 10 Events
-- IDs use fixed CUID2-style text for reproducibility.
-- Run after schema-v7.sql.
-- Safe to re-run: ON CONFLICT DO NOTHING on both tables.
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- QUICK LISTS
-- ─────────────────────────────────────────────────────────────
INSERT INTO quick_lists (id, slug, title, description, category, locale, is_published, is_featured) VALUES

-- ── EVENTS (featured) ────────────────────────────────────────
('ql_ev_bbq',        'bbq-party',           'BBQ Party',                  'Grilling essentials for a perfect backyard BBQ with family or friends.',          'event',   'id-ID', true, true),
('ql_ev_pool',       'pool-party',          'Pool Party',                 'Everything you need for a fun splashy weekend pool party.',                        'event',   'id-ID', true, true),
('ql_ev_birthday',   'birthday-party',      'Birthday Party',             'Cake, snacks, decorations — cover every birthday need in one list.',               'event',   'id-ID', true, true),
('ql_ev_lebaran',    'lebaran-feast',       'Lebaran / Idul Fitri Feast', 'Multi-day Lebaran prep: ketupat, opor, rendang, and all the kue kering.',          'event',   'id-ID', true, true),
('ql_ev_camping',    'camping-trip',        'Camping Trip',               'Food, cooking gear, and essentials for a weekend camping adventure.',              'event',   'id-ID', true, false),
('ql_ev_potluck',    'potluck-dinner',      'Potluck Dinner',             'Shared dinner prep — coordinate dishes and make sure nothing is forgotten.',       'event',   'id-ID', true, false),
('ql_ev_nye',        'new-year-party',      'New Year''s Eve Party',      'Ring in the new year with drinks, finger food, and party supplies.',               'event',   'id-ID', true, false),
('ql_ev_wedding',    'wedding-catering',    'Wedding Catering Prep',      'Bulk ingredient list for catering a traditional Indonesian wedding feast.',        'event',   'id-ID', true, false),
('ql_ev_arisan',     'office-gathering',    'Office Gathering / Arisan',  'Snacks, drinks, and door-prize supplies for a fun office get-together.',           'event',   'id-ID', true, false),
('ql_ev_babyshower', 'baby-shower',         'Baby Shower',                'Refreshments, decorations, and gift wrap supplies for a lovely baby shower.',      'event',   'id-ID', true, false),

-- ── INDONESIAN CUISINES ──────────────────────────────────────
('ql_01', 'nasi-goreng',          'Nasi Goreng',          'Classic Indonesian fried rice with kecap manis, egg, and aromatics.',                    'cuisine', 'id-ID', true, true),
('ql_02', 'rendang',              'Rendang',              'Slow-cooked Minangkabau beef in rich coconut and spice paste.',                          'cuisine', 'id-ID', true, true),
('ql_03', 'soto-ayam',            'Soto Ayam',            'Fragrant yellow chicken soup with turmeric, lemongrass, and vermicelli.',               'cuisine', 'id-ID', true, true),
('ql_04', 'gado-gado',            'Gado-Gado',            'Steamed vegetables and tofu topped with a thick peanut sauce.',                        'cuisine', 'id-ID', true, false),
('ql_05', 'nasi-padang',          'Nasi Padang',          'Padang-style rice with an assortment of rendang, gulai, and sambal sides.',             'cuisine', 'id-ID', true, true),
('ql_06', 'satay-ayam',           'Sate Ayam',            'Grilled chicken skewers served with peanut sauce and lontong.',                        'cuisine', 'id-ID', true, true),
('ql_07', 'mie-goreng',           'Mie Goreng',           'Indonesian stir-fried noodles with egg, vegetables, and sweet soy sauce.',              'cuisine', 'id-ID', true, false),
('ql_08', 'opor-ayam',            'Opor Ayam',            'Chicken braised in a mild coconut milk and spice broth.',                              'cuisine', 'id-ID', true, false),
('ql_09', 'ayam-goreng',          'Ayam Goreng',          'Crispy Indonesian fried chicken marinated in spices before frying.',                   'cuisine', 'id-ID', true, false),
('ql_10', 'sate-kambing',         'Sate Kambing',         'Goat meat skewers grilled over charcoal, served with sweet soy and shallots.',         'cuisine', 'id-ID', true, false),
('ql_11', 'nasi-kuning',          'Nasi Kuning',          'Festive turmeric-infused yellow rice cooked in coconut milk.',                         'cuisine', 'id-ID', true, false),
('ql_12', 'ketoprak',             'Ketoprak',             'Jakarta street food: rice cake, tofu, vermicelli, and peanut sauce.',                  'cuisine', 'id-ID', true, false),
('ql_13', 'lontong-cap-gomeh',    'Lontong Cap Gomeh',    'Peranakan rice cake served with opor, sambal goreng, and acar.',                       'cuisine', 'id-ID', true, false),
('ql_14', 'gulai-kambing',        'Gulai Kambing',        'Goat curry slow-simmered in coconut milk with warm spices.',                           'cuisine', 'id-ID', true, false),
('ql_15', 'ayam-betutu',          'Ayam Betutu',          'Balinese whole chicken packed with bumbu genep and slow-roasted.',                     'cuisine', 'id-ID', true, false),
('ql_16', 'ikan-bakar',           'Ikan Bakar',           'Grilled fish marinated in sweet soy, turmeric, and chili sambal.',                     'cuisine', 'id-ID', true, false),
('ql_17', 'pecel',                'Pecel',                'East Javanese salad of blanched vegetables with spicy peanut dressing.',               'cuisine', 'id-ID', true, false),
('ql_18', 'rujak',                'Rujak',                'Fresh fruit salad drizzled with a sweet, spicy, and tangy palm sugar sauce.',          'cuisine', 'id-ID', true, false),
('ql_19', 'nasi-lemak',           'Nasi Lemak',           'Coconut rice served with sambal, anchovies, peanuts, and hard-boiled egg.',            'cuisine', 'id-ID', true, false),
('ql_20', 'sop-ayam',             'Sop Ayam',             'Clear Indonesian chicken soup with vegetables and glass noodles.',                     'cuisine', 'id-ID', true, false),
('ql_21', 'dendeng-balado',       'Dendeng Balado',       'Thin crispy beef slices tossed in Padang-style red chili balado.',                     'cuisine', 'id-ID', true, false),
('ql_22', 'lodeh',                'Lodeh',                'Mild coconut milk vegetable stew with young jackfruit and tofu.',                      'cuisine', 'id-ID', true, false),
('ql_23', 'lalapan',              'Lalapan',              'Fresh raw vegetable platter served with sambal terasi and fried tempeh.',              'cuisine', 'id-ID', true, false),
('ql_24', 'arem-arem',            'Arem-Arem',            'Steamed rice rolls stuffed with spiced tempe or chicken filling.',                    'cuisine', 'id-ID', true, false),
('ql_25', 'sayur-lodeh',          'Sayur Lodeh',          'Coconut-based vegetable soup with cabbage, green beans, and eggplant.',               'cuisine', 'id-ID', true, false),
('ql_26', 'mie-aceh',             'Mie Aceh',             'Thick Acehnese noodles stir-fried with lamb or seafood in a bold spiced broth.',       'cuisine', 'id-ID', true, false),
('ql_27', 'coto-makassar',        'Coto Makassar',        'Rich Makassarese beef offal soup with spiced peanut-based broth.',                     'cuisine', 'id-ID', true, false),
('ql_28', 'pempek',               'Pempek',               'Palembang fish cake served with cuko — a sweet, sour, and spicy vinegar sauce.',       'cuisine', 'id-ID', true, false),
('ql_29', 'bakso',                'Bakso',                'Indonesian meatball soup with clear broth, noodles, and tofu.',                        'cuisine', 'id-ID', true, false),
('ql_30', 'rawon',                'Rawon',                'East Javanese black beef soup flavored with keluak nut.',                              'cuisine', 'id-ID', true, false),
('ql_31', 'sate-lilit',           'Sate Lilit',           'Balinese minced fish or pork satay wrapped around lemongrass skewers.',               'cuisine', 'id-ID', true, false),
('ql_32', 'tumpeng',              'Nasi Tumpeng',         'Ceremonial cone-shaped turmeric rice surrounded by assorted side dishes.',            'cuisine', 'id-ID', true, false),
('ql_33', 'gulai-ikan',           'Gulai Ikan',           'Fish simmered in a fragrant coconut curry with turmeric and galangal.',               'cuisine', 'id-ID', true, false),
('ql_34', 'bebek-betutu',         'Bebek Betutu',         'Balinese slow-cooked duck stuffed with herbs and wrapped in banana leaf.',            'cuisine', 'id-ID', true, false),
('ql_35', 'es-cendol',            'Es Cendol',            'Chilled dessert drink with pandan jelly, coconut milk, and palm sugar.',              'cuisine', 'id-ID', true, false),
('ql_36', 'klepon',               'Klepon',               'Pandan rice balls filled with palm sugar and rolled in grated coconut.',              'cuisine', 'id-ID', true, false),
('ql_37', 'dadar-gulung',         'Dadar Gulung',         'Pandan crepes rolled with sweet coconut and palm sugar filling.',                     'cuisine', 'id-ID', true, false),
('ql_38', 'onde-onde',            'Onde-Onde',            'Deep-fried sesame balls with sweet mung bean paste filling.',                         'cuisine', 'id-ID', true, false),
('ql_39', 'perkedel-jagung',      'Perkedel Jagung',      'Crispy corn fritters seasoned with shallots, garlic, and spring onion.',              'cuisine', 'id-ID', true, false),
('ql_40', 'tahu-gejrot',          'Tahu Gejrot',          'Cirebon fried tofu in a thin sweet and spicy vinegar sauce.',                         'cuisine', 'id-ID', true, false),
('ql_41', 'siomay',               'Siomay',               'Steamed fish dumplings served with peanut sauce, cabbage, and tofu.',                 'cuisine', 'id-ID', true, false),
('ql_42', 'batagor',              'Batagor',              'Fried tofu and fish dumplings served with peanut sauce.',                             'cuisine', 'id-ID', true, false),
('ql_43', 'martabak-telur',       'Martabak Telur',       'Savory pan-fried pastry stuffed with egg, meat, and spring onion.',                   'cuisine', 'id-ID', true, false),
('ql_44', 'martabak-manis',       'Martabak Manis',       'Thick sweet pancake filled with chocolate, cheese, or peanut.',                      'cuisine', 'id-ID', true, false),
('ql_45', 'pisang-goreng',        'Pisang Goreng',        'Golden deep-fried banana fritters, a popular Indonesian snack.',                      'cuisine', 'id-ID', true, false),
('ql_46', 'tempe-mendoan',        'Tempe Mendoan',        'Thinly sliced tempeh lightly battered and half-fried — soft and chewy.',              'cuisine', 'id-ID', true, false),
('ql_47', 'tahu-tempe-bacem',     'Tahu Tempe Bacem',     'Tofu and tempeh braised in palm sugar and spices until caramelized.',                 'cuisine', 'id-ID', true, false),
('ql_48', 'urab-sayuran',         'Urab Sayuran',         'Balinese blanched vegetable salad tossed in spiced grated coconut.',                  'cuisine', 'id-ID', true, false),
('ql_49', 'nasi-uduk',            'Nasi Uduk',            'Jakarta coconut milk rice cooked with lemongrass and bay leaf.',                      'cuisine', 'id-ID', true, false),
('ql_50', 'sayur-asem',           'Sayur Asem',           'Refreshing tamarind-based vegetable soup with corn and peanuts.',                     'cuisine', 'id-ID', true, false),
('ql_51', 'nasi-liwet',           'Nasi Liwet',           'Solo-style coconut rice served with opor chicken, egg, and sambal.',                  'cuisine', 'id-ID', true, false),
('ql_52', 'oseng-mercon',         'Oseng Mercon',         'Fiery stir-fried beef tendons and intestines in Yogyakarta chili style.',             'cuisine', 'id-ID', true, false),
('ql_53', 'bubur-ayam',           'Bubur Ayam',           'Smooth rice porridge topped with shredded chicken, cakwe, and crackers.',             'cuisine', 'id-ID', true, false),
('ql_54', 'kare-ayam',            'Kare Ayam',            'Indonesian chicken curry with coconut milk and a mild yellow spice paste.',           'cuisine', 'id-ID', true, false),
('ql_55', 'pepes-ikan',           'Pepes Ikan',           'Fish steamed in banana leaf with herbs, tomato, and chili.',                          'cuisine', 'id-ID', true, false),
('ql_56', 'nasi-goreng-kampung',  'Nasi Goreng Kampung',  'Village-style fried rice with anchovies, kangkung, and extra sambal.',               'cuisine', 'id-ID', true, false),
('ql_57', 'sop-buntut',           'Sop Buntut',           'Clear or fried oxtail soup with vegetables and a rich bone broth.',                  'cuisine', 'id-ID', true, false),
('ql_58', 'pindang-ikan',         'Pindang Ikan',         'Tangy sour fish soup with lemongrass, galangal, and tomato.',                        'cuisine', 'id-ID', true, false),
('ql_59', 'tumis-kangkung',       'Tumis Kangkung',       'Quick stir-fried water spinach with garlic, shrimp paste, and chili.',               'cuisine', 'id-ID', true, false),
('ql_60', 'bakwan-malang',        'Bakwan Malang',        'Malang-style meatball soup with fried wontons and clear broth.',                      'cuisine', 'id-ID', true, false),
('ql_61', 'capcay',               'Capcay',               'Chinese-Indonesian stir-fried mixed vegetables in savory oyster sauce.',              'cuisine', 'id-ID', true, false),
('ql_62', 'tongseng',             'Tongseng',             'Sweet and spicy goat or beef stew with cabbage and sweet soy.',                       'cuisine', 'id-ID', true, false),
('ql_63', 'nasi-timbel',          'Nasi Timbel',          'Sundanese banana-leaf-wrapped rice served with fried chicken and lalapan.',           'cuisine', 'id-ID', true, false),
('ql_64', 'mie-rebus',            'Mie Rebus',            'Boiled noodles in a thick sweet potato-based gravy with egg and shrimp.',            'cuisine', 'id-ID', true, false),
('ql_65', 'rujak-cingur',         'Rujak Cingur',         'Surabaya salad with cow snout, vegetables, and thick fermented shrimp sauce.',        'cuisine', 'id-ID', true, false),
('ql_66', 'nasi-kebuli',          'Nasi Kebuli',          'Arab-influenced spiced rice with goat meat and raisins.',                             'cuisine', 'id-ID', true, false),
('ql_67', 'sup-kepala-ikan',      'Sup Kepala Ikan',      'Fish head soup in a clear and sour broth with tomato and asam.',                     'cuisine', 'id-ID', true, false),
('ql_68', 'nasi-kucing',          'Nasi Kucing',          'Tiny Jogja-style rice portions with tempe, anchovy, or sambal.',                     'cuisine', 'id-ID', true, false),
('ql_69', 'nasi-krawu',           'Nasi Krawu',           'Gresik-style rice with shredded beef, serundeng, and sambal terasi.',                'cuisine', 'id-ID', true, false),
('ql_70', 'sate-padang',          'Sate Padang',          'Padang beef or offal skewers served with thick yellow curry sauce.',                  'cuisine', 'id-ID', true, false),
('ql_71', 'mie-ayam',             'Mie Ayam',             'Indonesian chicken noodles with savory soy-braised chicken topping.',                 'cuisine', 'id-ID', true, false),
('ql_72', 'ayam-rica-rica',       'Ayam Rica-Rica',       'Manado-style stir-fried chicken in a spicy tomato and chili sauce.',                  'cuisine', 'id-ID', true, false),
('ql_73', 'soto-betawi',          'Soto Betawi',          'Jakarta creamy beef and offal soup with coconut milk or fresh milk.',                 'cuisine', 'id-ID', true, false),
('ql_74', 'kerak-telor',          'Kerak Telor',          'Jakarta omelet of glutinous rice, egg, and dried shrimp cooked over charcoal.',      'cuisine', 'id-ID', true, false),
('ql_75', 'bubur-manado',         'Bubur Manado / Tinutuan','Manado mixed vegetable and corn porridge with kangkung and basil.',                 'cuisine', 'id-ID', true, false),
('ql_76', 'mie-kocok',            'Mie Kocok',            'Bandung beef trotter noodle soup with bean sprouts and a rich broth.',               'cuisine', 'id-ID', true, false),
('ql_77', 'tengkleng',            'Tengkleng',            'Solo thin goat bone soup with rich spiced broth, milder than gulai.',                'cuisine', 'id-ID', true, false),
('ql_78', 'semur-jengkol',        'Semur Jengkol',        'Jengkol beans braised in sweet soy and spice until tender.',                         'cuisine', 'id-ID', true, false),
('ql_79', 'lontong-sayur',        'Lontong Sayur',        'Rice cake in coconut milk vegetable curry, popular for breakfast.',                  'cuisine', 'id-ID', true, false),
('ql_80', 'nasi-bakar',           'Nasi Bakar',           'Seasoned rice wrapped in banana leaf and grilled until fragrant.',                   'cuisine', 'id-ID', true, false),
('ql_81', 'ikan-bakar-jimbaran',  'Ikan Bakar Jimbaran',  'Jimbaran-style grilled seafood basted with rich sambal matah.',                      'cuisine', 'id-ID', true, false),
('ql_82', 'soto-banjar',          'Soto Banjar',          'Banjar chicken soup with fragrant spices, vermicelli, and perkedel.',                'cuisine', 'id-ID', true, false),
('ql_83', 'ayam-taliwang',        'Ayam Taliwang',        'Lombok-style grilled chicken in an extra spicy chili and shrimp paste paste.',       'cuisine', 'id-ID', true, false),
('ql_84', 'nasi-campur-bali',     'Nasi Campur Bali',     'Balinese mixed rice with lawar, sate lilit, and multiple savory sides.',             'cuisine', 'id-ID', true, false),
('ql_85', 'garang-asem',          'Garang Asem',          'Central Javanese sour chicken dish steamed in banana leaf.',                         'cuisine', 'id-ID', true, false),
('ql_86', 'semur-daging',         'Semur Daging',         'Dutch-influenced Indonesian beef stew in sweet soy and nutmeg sauce.',               'cuisine', 'id-ID', true, false),
('ql_87', 'soto-mie',             'Soto Mie',             'Bogor-style noodle soup with beef, risol, and a clear spiced broth.',                'cuisine', 'id-ID', true, false),
('ql_88', 'babi-guling',          'Babi Guling',          'Balinese spit-roasted suckling pig rubbed with bumbu genep.',                        'cuisine', 'id-ID', true, false),
('ql_89', 'plecing-kangkung',     'Plecing Kangkung',     'Lombok blanched water spinach with a fiery tomato and shrimp paste sambal.',         'cuisine', 'id-ID', true, false),
('ql_90', 'mie-bangka',           'Mie Bangka',           'Bangka-style noodles with fish-based topping and spicy sambal.',                     'cuisine', 'id-ID', true, false),
('ql_91', 'ikan-patin-tempoyak',  'Ikan Patin Tempoyak',  'Catfish cooked in fermented durian paste with turmeric and chili.',                  'cuisine', 'id-ID', true, false),
('ql_92', 'gulai-tunjang',        'Gulai Tunjang',        'Padang beef trotter curry slow-cooked in coconut milk until gelatinous.',            'cuisine', 'id-ID', true, false),
('ql_93', 'nasi-bogana',          'Nasi Bogana',          'Tegal-style wrapped rice with opor, sambal, and salted egg.',                        'cuisine', 'id-ID', true, false),
('ql_94', 'bubur-kacang-hijau',   'Bubur Kacang Hijau',   'Sweet mung bean porridge with coconut milk and pandan.',                             'cuisine', 'id-ID', true, false),
('ql_95', 'serabi',               'Serabi',               'Soft pandan coconut milk pancakes from Solo or Bandung.',                            'cuisine', 'id-ID', true, false),
('ql_96', 'ketupat-lebaran',      'Ketupat Lebaran',      'Woven rice cake for Lebaran — served with opor, rendang, and sambal.',               'cuisine', 'id-ID', true, false),
('ql_97', 'lapis-legit',          'Lapis Legit',          'Rich Dutch-Indonesian spiced layer cake requiring dozens of egg yolks.',             'cuisine', 'id-ID', true, false),
('ql_98', 'sup-kimlo',            'Sup Kimlo',            'Chinese-Indonesian clear soup with glass noodles, mushroom, and meatball.',           'cuisine', 'id-ID', true, false),
('ql_99', 'nasi-goreng-seafood',  'Nasi Goreng Seafood',  'Fried rice loaded with prawns, squid, and fish cake.',                              'cuisine', 'id-ID', true, false),
('ql_100','kue-cubir',            'Kue Cubit',            'Small fluffy mini pancakes, half-cooked for a gooey center.',                        'cuisine', 'id-ID', true, false)

ON CONFLICT (id) DO NOTHING;


-- ─────────────────────────────────────────────────────────────
-- QUICK LIST ITEMS
-- ─────────────────────────────────────────────────────────────
INSERT INTO quick_list_items (id, quick_list_id, name, quantity, unit, is_optional, category, position) VALUES

-- ── BBQ Party ────────────────────────────────────────────────
('qli_ev_bbq_01', 'ql_ev_bbq', 'Beef ribs',             1,  'kg',   false, 'protein',   1),
('qli_ev_bbq_02', 'ql_ev_bbq', 'Chicken wings',         1,  'kg',   false, 'protein',   2),
('qli_ev_bbq_03', 'ql_ev_bbq', 'Lamb chops',            500,'gr',   true,  'protein',   3),
('qli_ev_bbq_04', 'ql_ev_bbq', 'Sausages',              500,'gr',   false, 'protein',   4),
('qli_ev_bbq_05', 'ql_ev_bbq', 'Corn on the cob',       4,  'pcs',  false, 'vegetable', 5),
('qli_ev_bbq_06', 'ql_ev_bbq', 'Kecap manis',           1,  'bottle',false,'sauce',     6),
('qli_ev_bbq_07', 'ql_ev_bbq', 'Sambal terasi',         1,  'jar',  false, 'sauce',     7),
('qli_ev_bbq_08', 'ql_ev_bbq', 'Garlic',                1,  'bulb', false, 'spice',     8),
('qli_ev_bbq_09', 'ql_ev_bbq', 'Cooking oil',           1,  'liter',false, 'pantry',    9),
('qli_ev_bbq_10', 'ql_ev_bbq', 'Charcoal',              2,  'kg',   false, 'equipment', 10),
('qli_ev_bbq_11', 'ql_ev_bbq', 'Aluminium foil',        1,  'roll', false, 'equipment', 11),
('qli_ev_bbq_12', 'ql_ev_bbq', 'Skewers',               1,  'pack', false, 'equipment', 12),
('qli_ev_bbq_13', 'ql_ev_bbq', 'Butter',                100,'gr',   false, 'dairy',     13),
('qli_ev_bbq_14', 'ql_ev_bbq', 'Lemon',                 3,  'pcs',  false, 'produce',   14),
('qli_ev_bbq_15', 'ql_ev_bbq', 'Disposable plates',     1,  'pack', false, 'equipment', 15),
('qli_ev_bbq_16', 'ql_ev_bbq', 'Bottled water',         6,  'pcs',  false, 'drink',     16),
('qli_ev_bbq_17', 'ql_ev_bbq', 'Soft drinks',           6,  'cans', true,  'drink',     17),
('qli_ev_bbq_18', 'ql_ev_bbq', 'Bread rolls',           8,  'pcs',  true,  'bakery',    18),

-- ── Pool Party ───────────────────────────────────────────────
('qli_ev_pool_01','ql_ev_pool','Bottled water',          12, 'pcs',  false, 'drink',     1),
('qli_ev_pool_02','ql_ev_pool','Soft drinks assorted',   12, 'cans', false, 'drink',     2),
('qli_ev_pool_03','ql_ev_pool','Juice boxes',            12, 'pcs',  true,  'drink',     3),
('qli_ev_pool_04','ql_ev_pool','Potato chips',           3,  'bags', false, 'snack',     4),
('qli_ev_pool_05','ql_ev_pool','Nachos & dip',           2,  'packs',true,  'snack',     5),
('qli_ev_pool_06','ql_ev_pool','Ice cubes',              2,  'bags', false, 'pantry',    6),
('qli_ev_pool_07','ql_ev_pool','Sunscreen SPF50',        1,  'bottle',false,'personal',  7),
('qli_ev_pool_08','ql_ev_pool','Disposable cups',        1,  'pack', false, 'equipment', 8),
('qli_ev_pool_09','ql_ev_pool','Paper napkins',          2,  'packs',false, 'equipment', 9),
('qli_ev_pool_10','ql_ev_pool','Watermelon',             1,  'pcs',  false, 'fruit',     10),
('qli_ev_pool_11','ql_ev_pool','Grapes',                 500,'gr',   true,  'fruit',     11),
('qli_ev_pool_12','ql_ev_pool','Skewers for fruit',      1,  'pack', true,  'equipment', 12),
('qli_ev_pool_13','ql_ev_pool','Trash bags',             1,  'roll', false, 'equipment', 13),

-- ── Birthday Party ───────────────────────────────────────────
('qli_ev_bday_01','ql_ev_birthday','All-purpose flour',  500,'gr',   false, 'baking',    1),
('qli_ev_bday_02','ql_ev_birthday','Eggs',               6,  'pcs',  false, 'dairy',     2),
('qli_ev_bday_03','ql_ev_birthday','Butter',             250,'gr',   false, 'dairy',     3),
('qli_ev_bday_04','ql_ev_birthday','Sugar',              300,'gr',   false, 'baking',    4),
('qli_ev_bday_05','ql_ev_birthday','Baking powder',      1,  'sachet',false,'baking',    5),
('qli_ev_bday_06','ql_ev_birthday','Milk',               500,'ml',   false, 'dairy',     6),
('qli_ev_bday_07','ql_ev_birthday','Whipping cream',     200,'ml',   false, 'dairy',     7),
('qli_ev_bday_08','ql_ev_birthday','Chocolate powder',   100,'gr',   true,  'baking',    8),
('qli_ev_bday_09','ql_ev_birthday','Candles',            1,  'pack', false, 'party',     9),
('qli_ev_bday_10','ql_ev_birthday','Balloons',           1,  'pack', false, 'party',     10),
('qli_ev_bday_11','ql_ev_birthday','Paper plates',       1,  'pack', false, 'equipment', 11),
('qli_ev_bday_12','ql_ev_birthday','Soft drinks',        6,  'bottles',false,'drink',    12),
('qli_ev_bday_13','ql_ev_birthday','Juice boxes',        12, 'pcs',  false, 'drink',     13),
('qli_ev_bday_14','ql_ev_birthday','Snack packs',        10, 'pcs',  true,  'snack',     14),
('qli_ev_bday_15','ql_ev_birthday','Party hats',         10, 'pcs',  true,  'party',     15),
('qli_ev_bday_16','ql_ev_birthday','Gift bags',          1,  'pack', true,  'party',     16),

-- ── Lebaran Feast ────────────────────────────────────────────
('qli_ev_lbr_01','ql_ev_lebaran','Beef (for rendang)',   2,  'kg',   false, 'protein',   1),
('qli_ev_lbr_02','ql_ev_lebaran','Whole chicken',        2,  'pcs',  false, 'protein',   2),
('qli_ev_lbr_03','ql_ev_lebaran','Ketupat (raw rice)',   1,  'kg',   false, 'carb',      3),
('qli_ev_lbr_04','ql_ev_lebaran','Coconut milk',         4,  'cans', false, 'dairy',     4),
('qli_ev_lbr_05','ql_ev_lebaran','Lemongrass',           5,  'stalks',false,'spice',     5),
('qli_ev_lbr_06','ql_ev_lebaran','Galangal',             1,  'pcs',  false, 'spice',     6),
('qli_ev_lbr_07','ql_ev_lebaran','Bay leaves',           10, 'pcs',  false, 'spice',     7),
('qli_ev_lbr_08','ql_ev_lebaran','Turmeric',             2,  'pcs',  false, 'spice',     8),
('qli_ev_lbr_09','ql_ev_lebaran','Shallots',             300,'gr',   false, 'spice',     9),
('qli_ev_lbr_10','ql_ev_lebaran','Garlic',               200,'gr',   false, 'spice',     10),
('qli_ev_lbr_11','ql_ev_lebaran','Candlenut',            100,'gr',   false, 'spice',     11),
('qli_ev_lbr_12','ql_ev_lebaran','Kecap manis',          2,  'bottles',false,'sauce',    12),
('qli_ev_lbr_13','ql_ev_lebaran','Eggs (for semur)',     12, 'pcs',  false, 'protein',   13),
('qli_ev_lbr_14','ql_ev_lebaran','Kue nastar (cookies)', 2,  'tins', true,  'snack',     14),
('qli_ev_lbr_15','ql_ev_lebaran','Kue kastengel',        2,  'tins', true,  'snack',     15),
('qli_ev_lbr_16','ql_ev_lebaran','Sirup marjan',         2,  'bottles',false,'drink',    16),
('qli_ev_lbr_17','ql_ev_lebaran','Bottled water crate',  1,  'crate',false, 'drink',     17),

-- ── Camping Trip ─────────────────────────────────────────────
('qli_ev_camp_01','ql_ev_camping','Instant noodles',     10, 'pcs',  false, 'pantry',    1),
('qli_ev_camp_02','ql_ev_camping','Canned tuna',         4,  'cans', false, 'protein',   2),
('qli_ev_camp_03','ql_ev_camping','Eggs',                6,  'pcs',  false, 'protein',   3),
('qli_ev_camp_04','ql_ev_camping','Bread',               1,  'loaf', false, 'bakery',    4),
('qli_ev_camp_05','ql_ev_camping','Peanut butter',       1,  'jar',  false, 'pantry',    5),
('qli_ev_camp_06','ql_ev_camping','Energy bars',         6,  'pcs',  false, 'snack',     6),
('qli_ev_camp_07','ql_ev_camping','Bottled water',       6,  'liters',false,'drink',     7),
('qli_ev_camp_08','ql_ev_camping','Gas canister (portable stove)',1,'pcs',false,'equipment',8),
('qli_ev_camp_09','ql_ev_camping','Lighter',             2,  'pcs',  false, 'equipment', 9),
('qli_ev_camp_10','ql_ev_camping','Trash bags',          1,  'roll', false, 'equipment', 10),
('qli_ev_camp_11','ql_ev_camping','Mosquito repellent',  1,  'bottle',false,'personal',  11),
('qli_ev_camp_12','ql_ev_camping','Wet wipes',           2,  'packs',false, 'personal',  12),
('qli_ev_camp_13','ql_ev_camping','First aid kit',       1,  'pcs',  false, 'health',    13),
('qli_ev_camp_14','ql_ev_camping','Folding knife',       1,  'pcs',  true,  'equipment', 14),
('qli_ev_camp_15','ql_ev_camping','Ground coffee sachet',5,  'sachets',false,'drink',    15),

-- ── Potluck Dinner ───────────────────────────────────────────
('qli_ev_pot_01','ql_ev_potluck','Paper plates',         2,  'packs',false, 'equipment', 1),
('qli_ev_pot_02','ql_ev_potluck','Plastic forks & spoons',2, 'packs',false, 'equipment', 2),
('qli_ev_pot_03','ql_ev_potluck','Serving bowls',        3,  'pcs',  true,  'equipment', 3),
('qli_ev_pot_04','ql_ev_potluck','Disposable food containers',10,'pcs',false,'equipment',4),
('qli_ev_pot_05','ql_ev_potluck','Cling wrap',           1,  'roll', false, 'equipment', 5),
('qli_ev_pot_06','ql_ev_potluck','Napkins',              2,  'packs',false, 'equipment', 6),
('qli_ev_pot_07','ql_ev_potluck','Bottled water',        12, 'pcs',  false, 'drink',     7),
('qli_ev_pot_08','ql_ev_potluck','Soft drinks assorted', 6,  'cans', true,  'drink',     8),
('qli_ev_pot_09','ql_ev_potluck','Ice cubes',            1,  'bag',  false, 'pantry',    9),
('qli_ev_pot_10','ql_ev_potluck','Label stickers (dish labels)',1,'pack',false,'equipment',10),

-- ── New Year's Eve Party ─────────────────────────────────────
('qli_ev_nye_01','ql_ev_nye','Chips assorted',           4,  'bags', false, 'snack',     1),
('qli_ev_nye_02','ql_ev_nye','Mini sandwiches bread',    2,  'loaves',false,'bakery',    2),
('qli_ev_nye_03','ql_ev_nye','Cheese slices',            200,'gr',   false, 'dairy',     3),
('qli_ev_nye_04','ql_ev_nye','Deli meat (ham/salami)',   200,'gr',   true,  'protein',   4),
('qli_ev_nye_05','ql_ev_nye','Soft drinks',              12, 'cans', false, 'drink',     5),
('qli_ev_nye_06','ql_ev_nye','Sparkling juice (non-alcoholic)',3,'bottles',false,'drink', 6),
('qli_ev_nye_07','ql_ev_nye','Ice cubes',                2,  'bags', false, 'pantry',    7),
('qli_ev_nye_08','ql_ev_nye','Plastic cups',             2,  'packs',false, 'equipment', 8),
('qli_ev_nye_09','ql_ev_nye','Balloons',                 2,  'packs',false, 'party',     9),
('qli_ev_nye_10','ql_ev_nye','Noise makers / terompet',  10, 'pcs',  true,  'party',     10),
('qli_ev_nye_11','ql_ev_nye','Sparklers',                1,  'pack', true,  'party',     11),
('qli_ev_nye_12','ql_ev_nye','Streamers',                2,  'rolls',true,  'party',     12),
('qli_ev_nye_13','ql_ev_nye','Bottled water',            12, 'pcs',  false, 'drink',     13),

-- ── Wedding Catering Prep ────────────────────────────────────
('qli_ev_wed_01','ql_ev_wedding','Chicken (whole)',       5,  'pcs',  false, 'protein',   1),
('qli_ev_wed_02','ql_ev_wedding','Beef (for rendang)',    3,  'kg',   false, 'protein',   2),
('qli_ev_wed_03','ql_ev_wedding','Rice',                 10,  'kg',   false, 'carb',      3),
('qli_ev_wed_04','ql_ev_wedding','Coconut milk',         10,  'cans', false, 'pantry',    4),
('qli_ev_wed_05','ql_ev_wedding','Shallots',             1,   'kg',   false, 'spice',     5),
('qli_ev_wed_06','ql_ev_wedding','Garlic',               500, 'gr',   false, 'spice',     6),
('qli_ev_wed_07','ql_ev_wedding','Galangal',             3,   'pcs',  false, 'spice',     7),
('qli_ev_wed_08','ql_ev_wedding','Lemongrass',           10,  'stalks',false,'spice',     8),
('qli_ev_wed_09','ql_ev_wedding','Bay leaves',           30,  'pcs',  false, 'spice',     9),
('qli_ev_wed_10','ql_ev_wedding','Kecap manis',          3,   'bottles',false,'sauce',    10),
('qli_ev_wed_11','ql_ev_wedding','Cooking oil',          3,   'liters',false,'pantry',    11),
('qli_ev_wed_12','ql_ev_wedding','Eggs',                 30,  'pcs',  false, 'protein',   12),
('qli_ev_wed_13','ql_ev_wedding','Tofu',                 2,   'kg',   true,  'protein',   13),
('qli_ev_wed_14','ql_ev_wedding','Tempeh',               1,   'kg',   true,  'protein',   14),
('qli_ev_wed_15','ql_ev_wedding','Bottled water crates', 3,   'crates',false,'drink',     15),
('qli_ev_wed_16','ql_ev_wedding','Syrup (sirup)',        4,   'bottles',false,'drink',    16),

-- ── Office Gathering / Arisan ────────────────────────────────
('qli_ev_ars_01','ql_ev_arisan','Snack boxes (assorted)',20,  'pcs',  false, 'snack',     1),
('qli_ev_ars_02','ql_ev_arisan','Bottled water',         20,  'pcs',  false, 'drink',     2),
('qli_ev_ars_03','ql_ev_arisan','Teh botol / iced tea',  20,  'pcs',  false, 'drink',     3),
('qli_ev_ars_04','ql_ev_arisan','Paper cups',            1,   'pack', false, 'equipment', 4),
('qli_ev_ars_05','ql_ev_arisan','Napkins',               2,   'packs',false, 'equipment', 5),
('qli_ev_ars_06','ql_ev_arisan','Gift wrap paper',       2,   'rolls',true,  'party',     6),
('qli_ev_ars_07','ql_ev_arisan','Ribbon',                1,   'roll', true,  'party',     7),
('qli_ev_ars_08','ql_ev_arisan','Name tag stickers',     1,   'pack', false, 'equipment', 8),
('qli_ev_ars_09','ql_ev_arisan','Prize envelopes',       5,   'pcs',  true,  'party',     9),
('qli_ev_ars_10','ql_ev_arisan','Coffee sachets',        20,  'pcs',  false, 'drink',     10),

-- ── Baby Shower ──────────────────────────────────────────────
('qli_ev_baby_01','ql_ev_babyshower','Mini sandwiches bread',2,'loaves',false,'bakery',   1),
('qli_ev_baby_02','ql_ev_babyshower','Cream cheese',     200, 'gr',   false, 'dairy',     2),
('qli_ev_baby_03','ql_ev_babyshower','Fruit platter mix',1,   'kg',   false, 'fruit',     3),
('qli_ev_baby_04','ql_ev_babyshower','Cupcake mix',      2,   'boxes',false, 'baking',    4),
('qli_ev_baby_05','ql_ev_babyshower','Cupcake liners',   1,   'pack', false, 'baking',    5),
('qli_ev_baby_06','ql_ev_babyshower','Whipping cream',   200, 'ml',   false, 'dairy',     6),
('qli_ev_baby_07','ql_ev_babyshower','Fruit juice assorted',6,'bottles',false,'drink',    7),
('qli_ev_baby_08','ql_ev_babyshower','Bottled water',    12,  'pcs',  false, 'drink',     8),
('qli_ev_baby_09','ql_ev_babyshower','Balloons (pastel)', 2,  'packs',false, 'party',     9),
('qli_ev_baby_10','ql_ev_babyshower','Banner decoration',1,   'pcs',  false, 'party',     10),
('qli_ev_baby_11','ql_ev_babyshower','Paper plates',     2,   'packs',false, 'equipment', 11),
('qli_ev_baby_12','ql_ev_babyshower','Gift bags',        5,   'pcs',  true,  'party',     12),
('qli_ev_baby_13','ql_ev_babyshower','Tissue box',       2,   'pcs',  false, 'personal',  13),

-- ─────────────────────────────────────────────────────────────
-- CUISINE ITEMS
-- ─────────────────────────────────────────────────────────────

-- ── Nasi Goreng ──────────────────────────────────────────────
('qli_01_01','ql_01','Day-old cooked rice',   3,  'cups',  false,'carb',   1),
('qli_01_02','ql_01','Eggs',                  2,  'pcs',   false,'protein',2),
('qli_01_03','ql_01','Garlic cloves',         3,  'pcs',   false,'spice',  3),
('qli_01_04','ql_01','Shallots',              3,  'pcs',   false,'spice',  4),
('qli_01_05','ql_01','Kecap manis',           2,  'tbsp',  false,'sauce',  5),
('qli_01_06','ql_01','Soy sauce',             1,  'tbsp',  false,'sauce',  6),
('qli_01_07','ql_01','Chili (cabe merah)',     2,  'pcs',   true, 'spice',  7),
('qli_01_08','ql_01','Spring onion',          2,  'stalks',false,'produce',8),
('qli_01_09','ql_01','Cooking oil',           2,  'tbsp',  false,'pantry', 9),
('qli_01_10','ql_01','Chicken (diced)',       100,'gr',    true, 'protein',10),
('qli_01_11','ql_01','Prawn crackers',        1,  'pack',  true, 'snack',  11),

-- ── Rendang ──────────────────────────────────────────────────
('qli_02_01','ql_02','Beef (chuck)',          1,  'kg',    false,'protein',1),
('qli_02_02','ql_02','Coconut milk',          2,  'cans',  false,'pantry', 2),
('qli_02_03','ql_02','Shallots',              200,'gr',    false,'spice',  3),
('qli_02_04','ql_02','Garlic',                6,  'cloves',false,'spice',  4),
('qli_02_05','ql_02','Lemongrass',            3,  'stalks',false,'spice',  5),
('qli_02_06','ql_02','Galangal',              2,  'cm',    false,'spice',  6),
('qli_02_07','ql_02','Turmeric',              2,  'cm',    false,'spice',  7),
('qli_02_08','ql_02','Ginger',                2,  'cm',    false,'spice',  8),
('qli_02_09','ql_02','Dried chili (cabe kering)',10,'pcs', false,'spice',  9),
('qli_02_10','ql_02','Candlenut (kemiri)',    5,  'pcs',   false,'spice',  10),
('qli_02_11','ql_02','Kaffir lime leaves',   5,  'pcs',   false,'spice',  11),
('qli_02_12','ql_02','Bay leaves',           3,  'pcs',   false,'spice',  12),

-- ── Soto Ayam ────────────────────────────────────────────────
('qli_03_01','ql_03','Whole chicken',         1,  'pcs',   false,'protein',1),
('qli_03_02','ql_03','Vermicelli (bihun)',    100,'gr',    false,'carb',   2),
('qli_03_03','ql_03','Turmeric',              3,  'cm',    false,'spice',  3),
('qli_03_04','ql_03','Galangal',              2,  'cm',    false,'spice',  4),
('qli_03_05','ql_03','Lemongrass',            2,  'stalks',false,'spice',  5),
('qli_03_06','ql_03','Kaffir lime leaves',   4,  'pcs',   false,'spice',  6),
('qli_03_07','ql_03','Shallots',             100,'gr',    false,'spice',  7),
('qli_03_08','ql_03','Garlic',               5,  'cloves',false,'spice',  8),
('qli_03_09','ql_03','Bean sprouts',         100,'gr',    false,'produce',9),
('qli_03_10','ql_03','Boiled eggs',           2,  'pcs',   false,'protein',10),
('qli_03_11','ql_03','Lime',                  2,  'pcs',   false,'produce',11),
('qli_03_12','ql_03','Fried shallots',        1,  'pack',  false,'pantry', 12),

-- ── Gado-Gado ────────────────────────────────────────────────
('qli_04_01','ql_04','Potatoes',             200,'gr',    false,'vegetable',1),
('qli_04_02','ql_04','Green beans',          100,'gr',    false,'vegetable',2),
('qli_04_03','ql_04','Bean sprouts',         100,'gr',    false,'vegetable',3),
('qli_04_04','ql_04','Cabbage',              100,'gr',    false,'vegetable',4),
('qli_04_05','ql_04','Tofu',                 100,'gr',    false,'protein', 5),
('qli_04_06','ql_04','Tempeh',               100,'gr',    false,'protein', 6),
('qli_04_07','ql_04','Boiled eggs',           2,  'pcs',   false,'protein', 7),
('qli_04_08','ql_04','Peanut butter',        150,'gr',    false,'sauce',   8),
('qli_04_09','ql_04','Kecap manis',           1,  'tbsp',  false,'sauce',   9),
('qli_04_10','ql_04','Lime',                  1,  'pcs',   false,'produce', 10),
('qli_04_11','ql_04','Chili',                 2,  'pcs',   true, 'spice',   11),
('qli_04_12','ql_04','Prawn crackers',        1,  'pack',  true, 'snack',   12),
('qli_04_13','ql_04','Lontong (rice cake)',   2,  'pcs',   true, 'carb',    13),

-- ── Sate Ayam ────────────────────────────────────────────────
('qli_06_01','ql_06','Chicken breast or thigh',500,'gr',  false,'protein', 1),
('qli_06_02','ql_06','Kecap manis',            3,  'tbsp', false,'sauce',   2),
('qli_06_03','ql_06','Peanut butter',          100,'gr',   false,'sauce',   3),
('qli_06_04','ql_06','Shallots',               3,  'pcs',  false,'spice',   4),
('qli_06_05','ql_06','Garlic',                 3,  'cloves',false,'spice',  5),
('qli_06_06','ql_06','Coriander powder',       1,  'tsp',  false,'spice',   6),
('qli_06_07','ql_06','Lime',                   2,  'pcs',  false,'produce', 7),
('qli_06_08','ql_06','Bamboo skewers',         1,  'pack', false,'equipment',8),
('qli_06_09','ql_06','Lontong',                4,  'pcs',  true, 'carb',    9),
('qli_06_10','ql_06','Chili (for sambal)',      3,  'pcs',  true, 'spice',   10),

-- ── Mie Goreng ───────────────────────────────────────────────
('qli_07_01','ql_07','Egg noodles',           200,'gr',    false,'carb',   1),
('qli_07_02','ql_07','Eggs',                   2,  'pcs',   false,'protein',2),
('qli_07_03','ql_07','Garlic',                 3,  'cloves',false,'spice',  3),
('qli_07_04','ql_07','Shallots',               2,  'pcs',   false,'spice',  4),
('qli_07_05','ql_07','Cabbage',               100,'gr',    false,'vegetable',5),
('qli_07_06','ql_07','Carrot',                 1,  'pcs',   false,'vegetable',6),
('qli_07_07','ql_07','Kecap manis',            2,  'tbsp',  false,'sauce',  7),
('qli_07_08','ql_07','Oyster sauce',           1,  'tbsp',  false,'sauce',  8),
('qli_07_09','ql_07','Chicken (diced)',       100,'gr',    true, 'protein', 9),
('qli_07_10','ql_07','Prawn crackers',         1,  'pack',  true, 'snack',  10),

-- ── Opor Ayam ────────────────────────────────────────────────
('qli_08_01','ql_08','Whole chicken (cut)',    1,  'pcs',   false,'protein',1),
('qli_08_02','ql_08','Coconut milk',           1,  'can',   false,'pantry', 2),
('qli_08_03','ql_08','Shallots',              100,'gr',    false,'spice',  3),
('qli_08_04','ql_08','Garlic',                 5,  'cloves',false,'spice',  4),
('qli_08_05','ql_08','Candlenut (kemiri)',     5,  'pcs',   false,'spice',  5),
('qli_08_06','ql_08','Coriander seeds',        1,  'tsp',   false,'spice',  6),
('qli_08_07','ql_08','Turmeric',               2,  'cm',    false,'spice',  7),
('qli_08_08','ql_08','Galangal',               2,  'cm',    false,'spice',  8),
('qli_08_09','ql_08','Lemongrass',             2,  'stalks',false,'spice',  9),
('qli_08_10','ql_08','Bay leaves',             3,  'pcs',   false,'spice',  10),
('qli_08_11','ql_08','Kaffir lime leaves',    4,  'pcs',   false,'spice',  11),

-- ── Bakso ────────────────────────────────────────────────────
('qli_29_01','ql_29','Ground beef',           500,'gr',    false,'protein',1),
('qli_29_02','ql_29','Tapioca starch',         50,'gr',    false,'pantry', 2),
('qli_29_03','ql_29','Garlic',                 5,  'cloves',false,'spice',  3),
('qli_29_04','ql_29','Salt',                   1,  'tsp',   false,'spice',  4),
('qli_29_05','ql_29','White pepper',           1,  'tsp',   false,'spice',  5),
('qli_29_06','ql_29','Ice water',             100,'ml',    false,'pantry', 6),
('qli_29_07','ql_29','Egg noodles',           200,'gr',    false,'carb',   7),
('qli_29_08','ql_29','Bean sprouts',          100,'gr',    false,'vegetable',8),
('qli_29_09','ql_29','Fried wontons',          1,  'pack',  true, 'snack',  9),
('qli_29_10','ql_29','Spring onion',           2,  'stalks',false,'produce',10),
('qli_29_11','ql_29','Fried shallots',         1,  'pack',  false,'pantry', 11),
('qli_29_12','ql_29','Sambal',                 1,  'jar',   true, 'sauce',  12),

-- ── Rawon ────────────────────────────────────────────────────
('qli_30_01','ql_30','Beef (brisket)',         500,'gr',    false,'protein',1),
('qli_30_02','ql_30','Keluak nuts (kluwek)',   5,  'pcs',   false,'spice',  2),
('qli_30_03','ql_30','Shallots',              100,'gr',    false,'spice',  3),
('qli_30_04','ql_30','Garlic',                 5,  'cloves',false,'spice',  4),
('qli_30_05','ql_30','Lemongrass',             2,  'stalks',false,'spice',  5),
('qli_30_06','ql_30','Galangal',               2,  'cm',    false,'spice',  6),
('qli_30_07','ql_30','Turmeric',               2,  'cm',    false,'spice',  7),
('qli_30_08','ql_30','Bean sprouts',          100,'gr',    false,'vegetable',8),
('qli_30_09','ql_30','Salted egg',             2,  'pcs',   true, 'protein',9),
('qli_30_10','ql_30','Spring onion',           2,  'stalks',false,'produce',10),

-- ── Pempek ───────────────────────────────────────────────────
('qli_28_01','ql_28','Mackerel fish (tenggiri)',400,'gr',  false,'protein',1),
('qli_28_02','ql_28','Tapioca starch',         200,'gr',   false,'pantry', 2),
('qli_28_03','ql_28','Eggs',                    2,  'pcs',  false,'protein',3),
('qli_28_04','ql_28','Garlic',                  3,  'cloves',false,'spice', 4),
('qli_28_05','ql_28','Salt',                    1,  'tsp',  false,'spice',  5),
('qli_28_06','ql_28','Palm sugar',             100,'gr',   false,'pantry', 6),
('qli_28_07','ql_28','Vinegar / asam jawa',     2,  'tbsp', false,'pantry', 7),
('qli_28_08','ql_28','Dried chili',             5,  'pcs',  false,'spice',  8),
('qli_28_09','ql_28','Cucumber (diced)',         1,  'pcs',  false,'produce',9),
('qli_28_10','ql_28','Ebi (dried shrimp)',      2,  'tbsp', true, 'protein',10),

-- ── Martabak Telur ───────────────────────────────────────────
('qli_43_01','ql_43','All-purpose flour',      250,'gr',   false,'baking', 1),
('qli_43_02','ql_43','Water',                  150,'ml',   false,'pantry', 2),
('qli_43_03','ql_43','Salt',                    1,  'tsp',  false,'spice',  3),
('qli_43_04','ql_43','Eggs',                    4,  'pcs',  false,'protein',4),
('qli_43_05','ql_43','Ground beef or chicken', 200,'gr',   false,'protein',5),
('qli_43_06','ql_43','Spring onion',            3,  'stalks',false,'produce',6),
('qli_43_07','ql_43','Leek (daun bawang)',       2,  'stalks',false,'produce',7),
('qli_43_08','ql_43','Curry powder',            1,  'tsp',  false,'spice',  8),
('qli_43_09','ql_43','Cooking oil',             3,  'tbsp', false,'pantry', 9),

-- ── Martabak Manis ───────────────────────────────────────────
('qli_44_01','ql_44','All-purpose flour',      250,'gr',   false,'baking', 1),
('qli_44_02','ql_44','Baking powder',           1,  'tsp',  false,'baking', 2),
('qli_44_03','ql_44','Baking soda',             1,  'tsp',  false,'baking', 3),
('qli_44_04','ql_44','Eggs',                    2,  'pcs',  false,'protein',4),
('qli_44_05','ql_44','Milk',                   300,'ml',   false,'dairy',  5),
('qli_44_06','ql_44','Sugar',                  100,'gr',   false,'baking', 6),
('qli_44_07','ql_44','Butter',                  50,'gr',   false,'dairy',  7),
('qli_44_08','ql_44','Chocolate sprinkles',     50,'gr',   false,'baking', 8),
('qli_44_09','ql_44','Grated cheese',          100,'gr',   true, 'dairy',  9),
('qli_44_10','ql_44','Condensed milk',           2,  'tbsp', true, 'dairy',  10),

-- ── Siomay ───────────────────────────────────────────────────
('qli_41_01','ql_41','Mackerel / tuna (minced)',300,'gr',  false,'protein',1),
('qli_41_02','ql_41','Tapioca starch',          100,'gr',  false,'pantry', 2),
('qli_41_03','ql_41','Garlic',                   3,  'cloves',false,'spice',3),
('qli_41_04','ql_41','Salt',                     1,  'tsp',  false,'spice', 4),
('qli_41_05','ql_41','White pepper',             1,  'tsp',  false,'spice', 5),
('qli_41_06','ql_41','Egg',                      1,  'pcs',  false,'protein',6),
('qli_41_07','ql_41','Wonton wrappers',          1,  'pack', false,'pantry', 7),
('qli_41_08','ql_41','Cabbage leaves',           4,  'pcs',  false,'vegetable',8),
('qli_41_09','ql_41','Tofu (firm)',             100,'gr',   false,'protein',9),
('qli_41_10','ql_41','Peanut butter',           100,'gr',   false,'sauce',  10),
('qli_41_11','ql_41','Lime',                     2,  'pcs',  false,'produce',11),
('qli_41_12','ql_41','Kecap manis',              2,  'tbsp', false,'sauce',  12),

-- ── Es Cendol ────────────────────────────────────────────────
('qli_35_01','ql_35','Pandan extract',          2,  'tbsp', false,'pantry', 1),
('qli_35_02','ql_35','Rice flour',             100,'gr',   false,'baking', 2),
('qli_35_03','ql_35','Tapioca starch',          50,'gr',   false,'pantry', 3),
('qli_35_04','ql_35','Palm sugar (gula jawa)', 200,'gr',   false,'pantry', 4),
('qli_35_05','ql_35','Coconut milk',            400,'ml',  false,'pantry', 5),
('qli_35_06','ql_35','Salt',                    1,  'pinch',false,'spice',  6),
('qli_35_07','ql_35','Ice cubes',               2,  'trays',false,'pantry', 7),

-- ── Klepon ───────────────────────────────────────────────────
('qli_36_01','ql_36','Glutinous rice flour',   200,'gr',   false,'baking', 1),
('qli_36_02','ql_36','Pandan juice',            50,'ml',   false,'pantry', 2),
('qli_36_03','ql_36','Palm sugar (filling)',   100,'gr',   false,'pantry', 3),
('qli_36_04','ql_36','Grated coconut',         150,'gr',   false,'pantry', 4),
('qli_36_05','ql_36','Salt',                    1,  'pinch',false,'spice',  5),

-- ── Bubur Ayam ───────────────────────────────────────────────
('qli_53_01','ql_53','Rice',                   150,'gr',   false,'carb',   1),
('qli_53_02','ql_53','Chicken breast',         200,'gr',   false,'protein',2),
('qli_53_03','ql_53','Ginger',                  2,  'cm',   false,'spice',  3),
('qli_53_04','ql_53','Garlic',                  3,  'cloves',false,'spice', 4),
('qli_53_05','ql_53','Spring onion',            2,  'stalks',false,'produce',5),
('qli_53_06','ql_53','Fried shallots',          1,  'pack', false,'pantry', 6),
('qli_53_07','ql_53','Soy sauce',               2,  'tbsp', false,'sauce',  7),
('qli_53_08','ql_53','Cakwe (fried dough)',     2,  'pcs',  true, 'snack',  8),
('qli_53_09','ql_53','Prawn crackers',          1,  'pack', true, 'snack',  9),
('qli_53_10','ql_53','Sesame oil',              1,  'tsp',  true, 'pantry', 10),

-- ── Pepes Ikan ───────────────────────────────────────────────
('qli_55_01','ql_55','Whole fish (tilapia / nila)',2,'pcs', false,'protein',1),
('qli_55_02','ql_55','Turmeric',                2,  'cm',   false,'spice',  2),
('qli_55_03','ql_55','Galangal',                2,  'cm',   false,'spice',  3),
('qli_55_04','ql_55','Lemongrass',              2,  'stalks',false,'spice', 4),
('qli_55_05','ql_55','Shallots',               50,  'gr',   false,'spice',  5),
('qli_55_06','ql_55','Garlic',                  3,  'cloves',false,'spice', 6),
('qli_55_07','ql_55','Red chili',               3,  'pcs',  false,'spice',  7),
('qli_55_08','ql_55','Tomato',                  2,  'pcs',  false,'produce',8),
('qli_55_09','ql_55','Basil leaves (kemangi)',  1,  'bunch',false,'produce',9),
('qli_55_10','ql_55','Banana leaves',           4,  'sheets',false,'equipment',10),
('qli_55_11','ql_55','Toothpicks / pins',       1,  'pack', false,'equipment',11),

-- ── Rendang (already done), skip to Nasi Kuning ──────────────
('qli_11_01','ql_11','Rice',                   300,'gr',   false,'carb',   1),
('qli_11_02','ql_11','Coconut milk',           200,'ml',   false,'pantry', 2),
('qli_11_03','ql_11','Turmeric',                3,  'cm',   false,'spice',  3),
('qli_11_04','ql_11','Lemongrass',              2,  'stalks',false,'spice', 4),
('qli_11_05','ql_11','Bay leaves',              3,  'pcs',  false,'spice',  5),
('qli_11_06','ql_11','Pandan leaf',             2,  'pcs',  false,'spice',  6),
('qli_11_07','ql_11','Salt',                    1,  'tsp',  false,'spice',  7),
('qli_11_08','ql_11','Fried chicken (side)',    1,  'pcs',  true, 'protein',8),
('qli_11_09','ql_11','Boiled egg',              2,  'pcs',  true, 'protein',9),
('qli_11_10','ql_11','Tempe orek (side)',        1,  'pack', true, 'protein',10),

-- ── Lapis Legit ──────────────────────────────────────────────
('qli_97_01','ql_97','Egg yolks',              20, 'pcs',   false,'baking', 1),
('qli_97_02','ql_97','Butter',                 250,'gr',    false,'dairy',  2),
('qli_97_03','ql_97','Sugar',                  200,'gr',    false,'baking', 3),
('qli_97_04','ql_97','All-purpose flour',       75,'gr',    false,'baking', 4),
('qli_97_05','ql_97','Spekkoek spice mix',      2,  'tbsp', false,'spice',  5),
('qli_97_06','ql_97','Condensed milk',           2,  'tbsp', true, 'dairy',  6),
('qli_97_07','ql_97','Vanilla extract',          1,  'tsp',  false,'baking', 7),

-- ── Ketupat Lebaran ──────────────────────────────────────────
('qli_96_01','ql_96','Ketupat casing (janur)',  10, 'pcs',  false,'equipment',1),
('qli_96_02','ql_96','Rice (raw)',             500, 'gr',   false,'carb',   2),
('qli_96_03','ql_96','Coconut milk',            2,  'cans', false,'pantry', 3),
('qli_96_04','ql_96','Chicken (for opor)',      1,  'pcs',  false,'protein',4),
('qli_96_05','ql_96','Beef (for rendang)',     500, 'gr',   true, 'protein',5),
('qli_96_06','ql_96','Shallots',              100, 'gr',   false,'spice',  6),
('qli_96_07','ql_96','Garlic',                  5,  'cloves',false,'spice', 7),
('qli_96_08','ql_96','Kecap manis',             2,  'bottles',false,'sauce',8),
('qli_96_09','ql_96','Sambal goreng tempe',     1,  'pack', true, 'protein',9),

-- ── Tumpeng ──────────────────────────────────────────────────
('qli_32_01','ql_32','Rice',                   500,'gr',   false,'carb',   1),
('qli_32_02','ql_32','Turmeric',                3,  'cm',   false,'spice',  2),
('qli_32_03','ql_32','Coconut milk',           200,'ml',   false,'pantry', 3),
('qli_32_04','ql_32','Lemongrass',              2,  'stalks',false,'spice', 4),
('qli_32_05','ql_32','Fried chicken',           1,  'pcs',  false,'protein',5),
('qli_32_06','ql_32','Tempe orek',              1,  'pack', false,'protein',6),
('qli_32_07','ql_32','Boiled eggs',             4,  'pcs',  false,'protein',7),
('qli_32_08','ql_32','Urab sayuran',            1,  'portion',false,'vegetable',8),
('qli_32_09','ql_32','Perkedel kentang',        4,  'pcs',  true, 'snack',  9),
('qli_32_10','ql_32','Teri balado (anchovy)',   1,  'pack', false,'protein',10),

-- ── Bubur Kacang Hijau ───────────────────────────────────────
('qli_94_01','ql_94','Mung beans (kacang hijau)',200,'gr', false,'pantry', 1),
('qli_94_02','ql_94','Coconut milk',            200,'ml',  false,'pantry', 2),
('qli_94_03','ql_94','Palm sugar',              100,'gr',  false,'pantry', 3),
('qli_94_04','ql_94','Pandan leaves',            2,  'pcs', false,'spice',  4),
('qli_94_05','ql_94','Ginger',                   2,  'cm',  false,'spice',  5),
('qli_94_06','ql_94','Salt',                     1,  'pinch',false,'spice', 6),

-- ── Serabi ───────────────────────────────────────────────────
('qli_95_01','ql_95','Rice flour',             200,'gr',   false,'baking', 1),
('qli_95_02','ql_95','Coconut milk',           300,'ml',   false,'pantry', 2),
('qli_95_03','ql_95','Pandan juice',            50,'ml',   false,'pantry', 3),
('qli_95_04','ql_95','Sugar',                   50,'gr',   false,'baking', 4),
('qli_95_05','ql_95','Salt',                    1,  'pinch',false,'spice',  5),
('qli_95_06','ql_95','Yeast',                   1,  'sachet',false,'baking',6),
('qli_95_07','ql_95','Palm sugar (sauce)',      100,'gr',  true, 'pantry', 7),

-- ── Ayam Goreng ──────────────────────────────────────────────
('qli_09_01','ql_09','Chicken (cut pieces)',    1,  'kg',   false,'protein',1),
('qli_09_02','ql_09','Turmeric',                2,  'cm',   false,'spice',  2),
('qli_09_03','ql_09','Garlic',                  5,  'cloves',false,'spice', 3),
('qli_09_04','ql_09','Shallots',               50,'gr',   false,'spice',  4),
('qli_09_05','ql_09','Coriander powder',        1,  'tsp',  false,'spice',  5),
('qli_09_06','ql_09','Salt',                    1,  'tsp',  false,'spice',  6),
('qli_09_07','ql_09','Bay leaves',              3,  'pcs',  false,'spice',  7),
('qli_09_08','ql_09','Lemongrass',              1,  'stalk',false,'spice',  8),
('qli_09_09','ql_09','Cooking oil',             500,'ml',  false,'pantry', 9),
('qli_09_10','ql_09','Lalapan (raw vegetables)',1,  'portion',true,'vegetable',10),
('qli_09_11','ql_09','Sambal terasi',           1,  'jar',  true, 'sauce',  11)

ON CONFLICT (id) DO NOTHING;
